# Generated by Django 2.2.5 on 2019-10-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='is_teacher',
            new_name='es_alumno',
        ),
    ]
