# Generated by Django 2.2.5 on 2019-10-06 13:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('EF', 'Efectivo'), ('CH', 'Cheque'), ('TA', 'Tarjeta Credito/Debito')], default='EF', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('active', models.NullBooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Pensiones',
                'verbose_name_plural': 'Pago de Pensiones',
            },
        ),
    ]
