# Generated by Django 2.2.5 on 2019-10-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0002_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpReporteCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promeEstudiante', models.DecimalField(decimal_places=3, max_digits=5)),
                ('promeAutoevaluacion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('promeEDD', models.DecimalField(decimal_places=3, max_digits=5)),
                ('promeEPP', models.DecimalField(decimal_places=3, max_digits=5)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona')),
            ],
        ),
    ]
