# Generated by Django 2.2.5 on 2019-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpreportecalificacion',
            name='promeAutoevaluacion',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='tmpreportecalificacion',
            name='promeEDD',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='tmpreportecalificacion',
            name='promeEPP',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='tmpreportecalificacion',
            name='promeEstudiante',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
