# Generated by Django 2.2.5 on 2019-10-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('periodo', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('active', models.NullBooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ruc', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('active', models.NullBooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad Educativa',
                'verbose_name_plural': 'Unidad Educativa',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.NullBooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('cedula', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('representante', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, default=None, null=True)),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Curso')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfil de Usuario',
            },
        ),
    ]
