# Generated by Django 2.2.5 on 2019-09-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField(default=0)),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respcalificacion_request_created', to='mantenimiento.Persona')),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificacion.TipoEvaluacion')),
            ],
        ),
    ]
