# Generated by Django 2.2.5 on 2019-09-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('calificacion', '0002_respcalificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstuStatusCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Asignatura')),
            ],
        ),
    ]
