# Generated by Django 2.2.5 on 2019-09-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Curso')),
            ],
            options={
                'verbose_name': 'Asignar Materias a Curso',
                'verbose_name_plural': 'Asignar Materias a los cursos',
            },
        ),
        migrations.CreateModel(
            name='DocenteCursoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.AsignaturaCurso', verbose_name='Materia por Curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignar Materia al Docente',
                'verbose_name_plural': 'Asignar Materia al Docente',
            },
        ),
        migrations.CreateModel(
            name='DocenteCalDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docenteCalificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentecaldocente_request_created', to='mantenimiento.Persona', verbose_name='Docente que califica')),
                ('profesorCalificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona', verbose_name='Docente que van a califica')),
            ],
            options={
                'verbose_name': 'Calificacion entre docentes',
                'verbose_name_plural': 'Calificacion entre docentes',
            },
        ),
        migrations.CreateModel(
            name='CursoEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Persona')),
            ],
            options={
                'verbose_name': 'Asignar Estudiante a curso',
                'verbose_name_plural': 'Asignar Estudiante a cursos',
            },
        ),
    ]
