# Generated by Django 2.2.5 on 2019-10-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaturacurso',
            options={'verbose_name': 'Asignar Materias a Curso', 'verbose_name_plural': 'Asignar Materias a los cur'},
        ),
    ]
